%YAML: 1.0

# line number
input_path_R: "/home/gct/LC-CurveModel/data/filter_test/tempvisual_points_R.txt"
input_path_Q: "/home/gct/LC-CurveModel/data/filter_test/templidar_points_Q.txt"
input_path_Q_raw: "/home/gct/LC-CurveModel/data/filter_test/kalman_out.txt"
output_path: "/home/gct/LC-CurveModel/data/filter_test/kalman_out_end.txt"
pcd_path: "/home/gct/LC-CurveModel/data/filter_test/kalman_out.pcd"