%YAML: 1.0

# line number
cam_calib: "cam0.yaml"
img_path: "/home/gct/LC-CurveModel/data/1-13guangzhou/image_2.png"
last_img_path: "/home/gct/LC-CurveModel/data/1-13guangzhou/image_1.png"
curve_points_file: "/home/gct/LC-CurveModel/data/1-13guangzhou/curve_points.txt"
result_flag_path: "/home/gct/LC-CurveModel/data/1-13guangzhou/optical_result.txt"