%YAML: 1.0

# line number
cam_calib: "cam0.yaml"
img_path: "/home/gct/LC_Modelcurve/data/1-13guangzhou/adjusted_1.png"
last_img_path: "/home/gct/LC_Modelcurve/data/1-13guangzhou/1224_1.png"
curve_points_file: "/home/gct/LC_Modelcurve/data/1-13guangzhou/curve_points.txt"
result_flag_path: "/home/gct/LC_Modelcurve/data/1-13guangzhou/optical_result.txt"