YAML: 1.0

# line number
line_num: 1

# input lidar points file
lidar_points_file: "/home/zyp/Lidar/LC-CurveModel/simulation/data/lidar_points.txt"

# camera yaml
cam_calib: "cam0.yaml"

# the known end point
end_point: [199.809, -4.48936, 2.19321]

# image path
image_path: "/home/zyp/DATA/lidar/0809/1.jpeg"

# points selected
selected_points: "/home/zyp/Lidar/LC-CurveModel/tools/points.txt"

# lidar-camera extrinsic
T_cam_lidar:
  rows: 4
  cols: 4
  dt: d
  data: [0.016182, -0.123492, 0.992214, 0.192,
         -0.02763, -0.99202,  -0.12302, 0.502,
         0.999487, -0.025433, -0.01947, -0.059,
         0.0, 0.0, 0.0, 1.0]