YAML: 1.0

# line number
line_num: 1
dark: 0

# camera yaml
cam_calib: "cam0.yaml"

# the known end point
end_point: [162.17, 4.90, 9.65]
# x sample
x_interval:
  start: 5.0
  end: 162

# image path
image_path: "/home/zyp/HD2/DATA/Transmisson/0912/test5/image_13.png"
# lidar points path
lidar_points_path: "/ssd/DATA/Transmisson/0912/test5/line_1.pcd"
# res path
res_path: "/home/zyp/Lidar/LC-CurveModel/res/wh/"

# points selected
# Note: please choose points from far away to near
selected_points: "/home/zyp/Lidar/LC-CurveModel/temp/points_0912_line1.txt"

# ex optimization
ex_optimization: 0
ref_lidar_points: "/home/zyp/Lidar/LC-CurveModel/lc_tools/lidar_ref.txt"
ref_image_points: "/home/zyp/Lidar/LC-CurveModel/lc_tools/points_ref.txt"

# matcher config(1: p2p  2: p2l)
matcher_type: 1
b_spline_num: 1000
sample: 0.2

# transmission model(0: parabola  1: catenary)
transmission_model: 0
y_optimize: 1           # 0: no optimize, 1: optimize

# lidar-camera extrinsic
T_cam_lidar:
  rows: 4
  cols: 4
  dt: d
  # ex for test_0912
  data: [0.0208246,  -0.999692,   0.013506, -0.0425305,
         0.00474393, -0.0134098,  -0.999899, 0.0922477,
         0.999772,  0.0208864, 0.00446337, -0.117265,
         0.0, 0.0, 0.0, 1.0]
#   data: [-0.00539706, -0.999968, -0.0058822, -0.0425305,
#          0.00511023, 0.00585463, -0.99997, 0.0922477,
#          0.999972, -0.00542695, 0.00507847, -0.117265,
#          0.0, 0.0, 0.0, 1.0]